name: Commit Message Check Reusable Workflow
on:
  workflow_call:
    inputs:      
      extra-options:
        required: false
        type: string
        default: ''
        description: 'Extra options as YAML/JSON object string'

permissions:
  contents: read
  
jobs:
  run-commit-msg-check:
    name: Run Commit Message Check
    if: ${{ github.event_name == 'pull_request' }}
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.head.sha }}
          fetch-depth: 0
      - name: Run Commit Message Check Action
        uses: qualcomm/commit-msg-check-action@v2.0.0
        with:
          base: ${{ github.event.pull_request.base.sha }}
          head: ${{ github.event.pull_request.head.sha }}
